name: simulation
root: ./
startup_window: solution
pre_window: export UAV_NAME=uav1; export WORLD_FILE=./world.yaml; export RUN_TYPE=simulation; export UAV_TYPE=t650; export WORLD_NAME=simulation; export SENSORS="garmin_down"
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - gazebo:
      layout: tiled
      panes:
        - waitForRos; roslaunch sarc_environment sarc_mrs.launch
  - status:
    layout: tiled
    panes:
      - waitForSimulation; roslaunch mrs_uav_status status.launch
  - spawn:
      layout: tiled
      panes:
        - waitForSimulation; rosservice call /mrs_drone_spawner/spawn "1 --enable-rangefinder --enable_bluefox_camera --pos_file `pwd`/pos/pos1.yaml";
          export UAV_NAME=uav1; waitForOdometry; roslaunch mrs_uav_general core.launch
        # - waitForSimulation; rosservice call /mrs_drone_spawner/spawn "2 --enable-rangefinder --enable_bluefox_camera --pos_file `pwd`/pos/pos2.yaml";
        #   export UAV_NAME=uav2; waitForOdometry; roslaunch mrs_uav_general core.launch
        # - waitForSimulation; rosservice call /mrs_drone_spawner/spawn "3 --enable-rangefinder --enable_bluefox_camera --pos_file `pwd`/pos/pos3.yaml";
        #   export UAV_NAME=uav3; waitForOdometry; roslaunch mrs_uav_general core.launch
        # - waitForSimulation; rosservice call /mrs_drone_spawner/spawn "4 --enable-rangefinder --enable_bluefox_camera --pos_file `pwd`/pos/pos4.yaml";
        #   export UAV_NAME=uav4; waitForOdometry; roslaunch mrs_uav_general core.launch
        # - waitForSimulation; rosservice call /mrs_drone_spawner/spawn "5 --enable-rangefinder --enable_bluefox_camera --pos_file `pwd`/pos/pos5.yaml";
        #   export UAV_NAME=uav5; waitForOdometry; roslaunch mrs_uav_general core.launch
        # - waitForSimulation; rosservice call /mrs_drone_spawner/spawn "6 --enable-rangefinder --enable_bluefox_camera --pos_file `pwd`/pos/pos6.yaml";
        #   export UAV_NAME=uav6; waitForOdometry; roslaunch mrs_uav_general core.launch
  - takeoff:
      layout: tiled
      panes:
        - waitForOdometry;export UAV_NAME=uav1;
          sleep 15;
          rosservice call /$UAV_NAME/control_manager/motors 1;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard;
          rosservice call /$UAV_NAME/uav_manager/takeoff
        # - waitForOdometry;export UAV_NAME=uav2;
        #   sleep 15;
        #   rosservice call /$UAV_NAME/control_manager/motors 1;
        #   rosservice call /$UAV_NAME/mavros/cmd/arming 1;
        #   rosservice call /$UAV_NAME/mavros/set_mode 0 offboard;
        #   rosservice call /$UAV_NAME/uav_manager/takeoff
        # - waitForOdometry;export UAV_NAME=uav3;
        #   sleep 15;
        #   rosservice call /$UAV_NAME/control_manager/motors 1;
        #   rosservice call /$UAV_NAME/mavros/cmd/arming 1;
        #   rosservice call /$UAV_NAME/mavros/set_mode 0 offboard;
        #   rosservice call /$UAV_NAME/uav_manager/takeoff
        # - waitForOdometry;export UAV_NAME=uav4;
        #   sleep 15;
        #   rosservice call /$UAV_NAME/control_manager/motors 1;
        #   rosservice call /$UAV_NAME/mavros/cmd/arming 1;
        #   rosservice call /$UAV_NAME/mavros/set_mode 0 offboard;
        #   rosservice call /$UAV_NAME/uav_manager/takeoff
        # - waitForOdometry;export UAV_NAME=uav5;
        #   sleep 15;
        #   rosservice call /$UAV_NAME/control_manager/motors 1;
        #   rosservice call /$UAV_NAME/mavros/cmd/arming 1;
        #   rosservice call /$UAV_NAME/mavros/set_mode 0 offboard;
        #   rosservice call /$UAV_NAME/uav_manager/takeoff
        # - waitForOdometry;export UAV_NAME=uav6;
        #   sleep 15;
        #   rosservice call /$UAV_NAME/control_manager/motors 1;
        #   rosservice call /$UAV_NAME/mavros/cmd/arming 1;
        #   rosservice call /$UAV_NAME/mavros/set_mode 0 offboard;
        #   rosservice call /$UAV_NAME/uav_manager/takeoff
  - solution:
    layout: tiled
    panes:
      - waitForOdometry; roslaunch carcara vision.launch